
positions = ["UpperLeft" "Top" "UpperRight";
        "Left" "Center" "Right";
        "LowerLeft" "Bottom" "LowerRight"];

import CFS.Experiment.* ...
    CFS.Element.Screen.* ...
    CFS.Element.Data.* ...
    CFS.Element.Evidence.* ...
    CFS.Element.Stimulus.*


% Initiate an object, for visual priming CFS use experiment = VPCFS(),
% for breaking CFS use experiment = BCFS(),
% for visual adaptation CFS use experiment = VACFS().

experiment = BCFS();

experiment.fixation = Fixation( ...
    duration=1, ...
    arm_length=20, ...
    line_width=4, ...
    color='#525252');

experiment.stimulus = SuppressedStimulus( ...
    './Images/suppressed_images', ...
    appearance_delay=1, ...
    fade_in_duration=0, ...
    show_duration=3, ...
    fade_out_duration=0, ...
    position='Center', ...
    size=0.3, ...
    padding=0.5, ...
    xy_ratio=1, ...
    contrast=1, ...
    rotation=0, ...
    n_rotations_per_trial=1, ...
    rotations_variance=0);

experiment.masks = Masks( ...
    './Masks/', ...
    temporal_frequency=10, ...
    duration=5, ...
    mondrians_shape=1, ...
    mondrians_color=15, ...
    position='Center', ...
    size=1, ...
    padding=0, ...
    xy_ratio=1, ...
    contrast=1, ...
    rotation=0);


if class(experiment) == "CFS.Experiment.VPCFS" || class(experiment) == "CFS.Experiment.VACFS"
    
    experiment.target = TargetStimulus( ...
        './Images/Target_images', ...
        duration=0.9, ...
        position=experiment.stimulus.position, ...
        size=experiment.stimulus.size, ...
        padding=experiment.stimulus.padding, ...
        xy_ratio=experiment.stimulus.xy_ratio, ...
        contrast=experiment.stimulus.contrast, ...
        rotation=experiment.stimulus.rotation);

    experiment.mafc = ImgMAFC( ...
        keys={'LeftArrow', 'RightArrow'}, ...
        title='Which one have you seen?', ...
        position='Center', ...
        size=0.75, ...
        xy_ratio=1);

%     experiment.mafc = TextMAFC( ...
%         keys={'LeftArrow', 'RightArrow'}, ...
%         title='Which one have you seen?', ...
%         options={'Simulacra', 'Simulation'});

    experiment.pas = PAS( ...
        keys={'0)', '1!', '2@', '3#'}, ...
        title='How clear was the experience?',...
        options={ ...
        '0: No experience', ...
        '1: A weak experience', ... 
        '2: An almost clear experience', ...
        '3: A clear experience'});
    
end

if class(experiment) == "CFS.Experiment.BCFS" || class(experiment) == "CFS.Experiment.VACFS"

    experiment.stimulus_break = BreakResponse( ...
        keys={'LeftArrow', 'RightArrow'});

end


if ~exist('.temp', 'dir')
    mkdir('.temp')
end
save('.temp\experiment.mat', 'experiment')

n_blocks = 5;
n_trials = [5,6,4,5,7];

trial_matrix = cell(1, n_blocks);
for block = 1:n_blocks
    for trial = 1:n_trials(block)
        load('.temp\experiment.mat');
        experiment.stimulus.indices = randi(9, [3,3]);
        %experiment.target.index = randi(2);
        X = randperm(numel(positions));
        %experiment.stimulus.position = reshape(positions(X), size(positions));
        trial_matrix{block}{trial} = experiment;
    end
end

rmdir('.temp', 's')
save('TrialMatrices\experiment.mat', 'trial_matrix')
