function b_flash(obj)
% Flashes stimuli, masks, fixations.
%
% This is the main method for flashing backward VM and recording its timings.
% 

    obj.draw(fixation=true)
    [vbl, obj.fixation.onset] = Screen('Flip', obj.screen.window);
    
    obj.draw(fixation=true, stim=true)
    [vbl, obj.stimulus.onset] = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.fixation.duration-0.5*obj.screen.inter_frame_interval);

    if obj.stimulus.duration < obj.mask.soa

        [vbl, obj.stimulus.offset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.stimulus.duration-0.5*obj.screen.inter_frame_interval);

        obj.draw(fixation=true, mask=obj.mask)
        [vbl, obj.mask.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.mask.soa-obj.stimulus.duration-0.5*obj.screen.inter_frame_interval);
    else
        obj.draw(fixation=true, mask=obj.mask)
        [vbl, obj.mask.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.mask.soa-0.5*obj.screen.inter_frame_interval);
        obj.stimulus.offset = obj.mask.onset;
    end

    obj.draw(fixation=true)
    [vbl, obj.mask.offset] = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.mask.duration-0.5*obj.screen.inter_frame_interval);

    obj.draw(fixation=true)
    Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.mask.blank-0.5*obj.screen.inter_frame_interval);

end