function s_flash(obj)
% Flashes stimuli, masks, fixations.
%
% This is the main method for flashing simulatenous VM and recording its timings.
% 

    obj.draw(obj, fixation=true)
    obj.fixation.onset = Screen('Flip', obj.screen.window);

    obj.draw(obj, fixation=true, stim=true, mask=obj.mask)
    obj.stimulus.onset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.fixation.onset+obj.fixation.duration-obj.screen.inter_frame_interval/2);
    obj.mask.onset = obj.stimulus.onset;
    
    obj.draw(obj, fixation=true, stim=true)
    obj.stimulus.onset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.fixation.onset+obj.fixation.duration-obj.screen.inter_frame_interval/2);

    if obj.stimulus.duration < obj.mask.soa

        obj.stimulus.offset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.onset+obj.stimulus.duration-obj.screen.inter_frame_interval/2);

        obj.draw(obj, fixation=true, mask=true)
        obj.mask.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.offset+obj.mask.soa-obj.stimulus.duration-obj.screen.inter_frame_interval/2);
    else
        obj.draw(obj, fixation=true, mask=true)
        obj.mask.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.onset+obj.mask.soa-obj.screen.inter_frame_interval/2);
        obj.stimulus.offset = obj.mask.onset;
    end

    obj.draw(obj, fixation=true)
    obj.mask.offset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.mask.onset+obj.mask.duration-obj.screen.inter_frame_interval/2);

    obj.draw(obj, fixation=true)
    Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.mask.onset+obj.mask.blank-obj.screen.inter_frame_interval/2);

end