function load_flashing_parameters(obj, screen)
% LOAD_FLASHING_PARAMETERS Calculates contrasts arrays for flashing.

    obj.textures.index = obj.textures.PTB_indices{obj.index};
    obj.image_name = obj.textures.images_names(obj.index);
    obj.contrasts_in = obj.contrast/ ...
        (obj.fade_in_duration*screen.frame_rate+1): ...
        obj.contrast/(obj.fade_in_duration*screen.frame_rate+1): ...
        obj.contrast;
    obj.contrasts_out = obj.contrast/ ...
        (obj.fade_out_duration*screen.frame_rate+1): ...
        obj.contrast/(obj.fade_out_duration*screen.frame_rate+1): ...
        obj.contrast;
    
    N_ROTATIONS = 5;
    VARIANCE = 60;
    rotation_time = obj.fade_in_duration+obj.show_duration+obj.fade_out_duration;
    time_per_rotation = rotation_time/N_ROTATIONS;
    frames_per_rotation = time_per_rotation*screen.frame_rate;
    obj.rotation_array = arrayfun(@(n) (obj.rotation+VARIANCE/2-randi(VARIANCE)), ...
        1:N_ROTATIONS);
    obj.rotation_indices = arrayfun(@(n) (ceil(n/frames_per_rotation)), ...
        1:(rotation_time*screen.frame_rate));
    obj.rotation_indices = [obj.rotation_indices, obj.rotation_indices(end)];

end