function cycles_per_deg = cycles_per_pixel2cycles_per_deg( ...
    cycles_per_pix, ...
    display_width_cm, ...
    display_width_pixels, ...
    viewing_distance ...
    )
    
    pixel_size_cm = display_width_cm/display_width_pixels;
    cycles_per_rad = cycles_per_pix*viewing_distance/pixel_size_cm;
    cycles_per_deg = cycles_per_rad*(pi/180);

end

