function draw(obj, parameters)
% Optionally draws fixation, stimulus and mask.
%
% Args:
%   fixation: bool
%   stim: bool
%   mask: :class:`CFSVM.Element.Stimulus.Mask`
%

    arguments
        obj
        parameters.fixation = false
        parameters.stim = false
        parameters.mask = false
    end

    if parameters.fixation ~= false
        for n = 1:length(obj.fixation.args)
            % Screen cross
            Screen(obj.fixation.args{n}{:});
        end
    end
    
    if parameters.stim ~= false
        Screen( ...
            'DrawTexture', ...
            obj.screen.window, ...
            obj.stimulus.textures.PTB_indices{obj.stimulus.index}, ...
            [], ...
            obj.stimulus.rect, ...
            obj.stimulus.rotation, ...
            [], ...
            obj.stimulus.contrast);
    end

    if parameters.mask ~= false
        Screen( ...
            'DrawTexture', ...
            obj.screen.window, ...
            parameters.mask.textures.PTB_indices{1}, ...
            [], ...
            parameters.mask.rect, ...
            parameters.mask.rotation, ...
            [], ...
            parameters.mask.contrast);
    end

end