function f_flash(obj)
% Flashes stimuli, masks, fixations and checkframe.
%
% This is the main method for flashing CFS and recording its timings.
% 
% Args:
%   vbl: An integer for vertical retrace timing from the fixation.show().
%

    obj.draw(fixation=true)
    obj.fixation.onset = Screen('Flip', obj.screen.window);

    obj.draw(fixation=true, mask=obj.mask)
    obj.mask.onset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.fixation.onset+obj.fixation.duration-obj.screen.inter_frame_interval/2);
    
    if obj.mask.duration < obj.mask.soa

        obj.mask.offset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.mask.onset+obj.mask.duration-obj.screen.inter_frame_interval/2);

        obj.draw(fixation=true, stim=true)
        obj.stimulus.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.mask.offset+obj.mask.soa-obj.mask.duration-obj.screen.inter_frame_interval/2);
    else
        obj.draw(fixation=true, stim=true)
        obj.stimulus.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.mask.onset+obj.mask.soa-obj.screen.inter_frame_interval/2);
        obj.mask.offset = obj.stimulus.onset;
    end


    obj.draw(fixation=true)
    obj.stimulus.offset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.stimulus.onset+obj.stimulus.duration-obj.screen.inter_frame_interval/2);

    obj.draw(fixation=true)
    Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.stimulus.onset+obj.stimulus.blank-obj.screen.inter_frame_interval/2);


end