function flash(obj)
% Flashes stimuli, masks, fixations and checkframe.
%
% This is the main method for flashing CFS and recording its timings.
% 
% Args:
%   vbl: An integer for vertical retrace timing from the fixation.show().
%

    obj.draw(fixation=true)
    obj.fixation.onset = Screen('Flip', obj.screen.window);
    
    obj.draw(fixation=true, mask=obj.f_mask)
    obj.f_mask.onset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.fixation.onset+obj.fixation.duration-obj.screen.inter_frame_interval/2);
    

    if obj.f_mask.duration < obj.f_mask.soa

        obj.f_mask.offset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.f_mask.onset+obj.f_mask.duration-obj.screen.inter_frame_interval/2);

        obj.draw(fixation=true, stim=true)
        obj.stimulus.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.f_mask.offset+obj.f_mask.soa-obj.f_mask.duration-obj.screen.inter_frame_interval/2);
    else
        obj.draw(fixation=true, stim=true)
        obj.stimulus.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.f_mask.onset+obj.f_mask.soa-obj.screen.inter_frame_interval/2);
        obj.f_mask.offset = obj.stimulus.onset;
    end


    if obj.stimulus.duration < obj.b_mask.soa

        obj.stimulus.offset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.onset+obj.stimulus.duration-obj.screen.inter_frame_interval/2);

        obj.draw(fixation=true, mask=obj.b_mask)
        obj.b_mask.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.offset+obj.b_mask.soa-obj.stimulus.duration-obj.screen.inter_frame_interval/2);
    else
        obj.draw(fixation=true, mask=obj.b_mask)
        obj.b_mask.onset = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            obj.stimulus.onset+obj.b_mask.soa-obj.screen.inter_frame_interval/2);
        obj.stimulus.offset = obj.b_mask.onset;
    end

    obj.draw(fixation=true)
    obj.b_mask.offset = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.b_mask.onset+obj.b_mask.duration-obj.screen.inter_frame_interval/2);

    obj.draw(fixation=true)
    Screen( ...
        'Flip', ...
        obj.screen.window, ...
        obj.b_mask.onset+obj.b_mask.blank-obj.screen.inter_frame_interval/2);

end