function orientation_filter(obj, orientation, sigma)
    [XX, YY] = meshgrid( ...
        -obj.padded_stimuli_dim(1)/2:obj.padded_stimuli_dim(1)/2-1, ...
        obj.padded_stimuli_dim(1)/2:-1:-(obj.padded_stimuli_dim(1)/2-1));
    theta = atan2(-YY,XX);  % orientation map
    ori_filter = orientation_filter( ...
        theta, ...
        orientation, ...
        sigma);
    obj.fft_stimuli = obj.fft_stimuli .* ori_filter;
end