function flash(obj)
% Flashes stimuli, masks, fixations and checkframe.
%
% This is the main method for flashing CFS and recording its timings.
% 
% Args:
%   vbl: An integer for vertical retrace timing from the fixation.show().
%

    obj.draw(fixation=true)
    [vbl, obj.fixation.onset] = Screen('Flip', obj.screen.window);
    
    obj.draw(fixation=true, mask=obj.f_mask)
    [vbl, obj.f_mask.onset] = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.fixation.duration-0.5*obj.screen.inter_frame_interval);
    

    if obj.f_mask.duration < obj.f_mask.soa

        [vbl, obj.f_mask.offset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.f_mask.duration-0.5*obj.screen.inter_frame_interval);

        obj.draw(fixation=true, stim=true)
        [vbl, obj.stimulus.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.f_mask.soa-obj.f_mask.duration-0.5*obj.screen.inter_frame_interval);
    else
        obj.draw(fixation=true, stim=true)
        [vbl, obj.stimulus.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.f_mask.soa-0.5*obj.screen.inter_frame_interval);
        obj.f_mask.offset = obj.stimulus.onset;
    end


    if obj.stimulus.duration < obj.b_mask.soa

        [vbl, obj.stimulus.offset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.stimulus.duration-0.5*obj.screen.inter_frame_interval);

        obj.draw(fixation=true, mask=obj.b_mask)
        [vbl, obj.b_mask.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.b_mask.soa-obj.stimulus.duration-0.5*obj.screen.inter_frame_interval);
    else
        obj.draw(fixation=true, mask=obj.b_mask)
        [vbl, obj.b_mask.onset] = Screen( ...
            'Flip', ...
            obj.screen.window, ...
            vbl+obj.b_mask.soa-0.5*obj.screen.inter_frame_interval);
        obj.stimulus.offset = obj.b_mask.onset;
    end

    obj.draw(fixation=true)
    [vbl, obj.b_mask.offset] = Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.b_mask.duration-0.5*obj.screen.inter_frame_interval);

    obj.draw(fixation=true)
    Screen( ...
        'Flip', ...
        obj.screen.window, ...
        vbl+obj.b_mask.blank-0.5*obj.screen.inter_frame_interval);

end