function load_flashing_parameters(obj, screen)
    %METHOD2 Summary of this method goes here
    %   Detailed explanation goes here
    obj.waitframe = Screen('NominalFrameRate', screen.window)/obj.temporal_frequency;
    obj.delay=1/obj.temporal_frequency - 0.5*screen.inter_frame_interval;

    obj.n_cumul_before_fade_out = ... 
        obj.n_while_stimulus + ...
        obj.n_while_fade_in + ...
        obj.n_before_stimulus;

    obj.indices_while_fade_in = arrayfun(@(n) (floor(obj.n_before_stimulus+(n-1)/obj.waitframe)), ...
        1:(1+obj.n_while_fade_in*obj.waitframe));

    obj.indices_while_fade_out = arrayfun(@(n) (floor(obj.n_cumul_before_fade_out+...
        (obj.n_while_fade_out*obj.waitframe-n)/obj.waitframe)), ...
        1:(obj.n_while_fade_out*obj.waitframe-1));
end