classdef Mondrians < CFSVM.Element.Stimulus.Stimulus
% Manipulating Mondrian masks.
%
% Derived from :class:`~CFSVM.Element.Stimulus.Stimulus`.
%


    properties (Constant)
        
        % Parameters to parse into the processed results table.
        RESULTS = {'onset', 'offset'}

    end


    properties

        % Float in Hz, number of masks flashed per one second.
        temporal_frequency {mustBeNonnegative}
        % Int - overall max number of masks from blocks and trials.
        n_max {mustBeNonnegative, mustBeInteger}
        % 1D array representing masks index for every frame.
        indices {mustBeInteger}
        % Cell array storing arguments for PTB's Screen('DrawTextures') for
        % masks, stimuli, fixation and checkframe.
        args cell
        % 1D array recording onset times of every frame.
        vbls {mustBeNonnegative}
        % Path to .mat file generated by CFS_crafter.
        crafter_masks

    end


    methods

        function obj = Mondrians(parameters)
        %
        % Args:
        %   dirpath: :attr:`CFSVM.Element.Stimulus.Stimulus.dirpath`
        %   temporal_frequency: :attr:`~CFSVM.Element.Stimulus.Mondrians.temporal_frequency`
        %   duration: :attr:`CFSVM.Element.TemporalElement.duration`
        %   position: :attr:`CFSVM.Element.Stimulus.Stimulus.position`
        %   xy_ratio: :attr:`CFSVM.Element.Stimulus.Stimulus.xy_ratio`
        %   size: :attr:`CFSVM.Element.Stimulus.Stimulus.size`
        %   padding: :attr:`CFSVM.Element.Stimulus.Stimulus.padding`
        %   rotation: :attr:`CFSVM.Element.Stimulus.Stimulus.rotation`
        %   contrast: :attr:`CFSVM.Element.SpatialElement.contrast`
        %   blank: :attr:`CFSVM.Element.Stimulus.Stimulus.blank`
        %   crafter_masks: :attr:`~CFSVM.Element.Stimulus.Mondrians.crafter_masks`
        %   manual_rect: :attr:`CFSVM.Element.Stimulus.Stimulus.manual_rect`
        %
            arguments
                parameters.dirpath = ''
                parameters.temporal_frequency = 10
                parameters.duration = 5
                parameters.position = "Center"
                parameters.xy_ratio = 1
                parameters.size = 1
                parameters.padding = 0
                parameters.rotation = 0
                parameters.contrast = 1
                parameters.blank = 0
                parameters.crafter_masks = ''
                parameters.manual_rect
            end

            parameters_names = fieldnames(parameters);
            
            for name = 1:length(parameters_names)
                obj.(parameters_names{name}) = parameters.(parameters_names{name});
            end

        end
        
        get_max(obj, trial_matrices)
        shuffle(obj)
        load_rect_parameters(obj, screen, is_left_suppression)
        load_flashing_parameters(obj, screen)
        import_from_crafter(obj, window)

    end

end

