function load_rect_parameters(obj)
%LOAD_RECT_PARAMETERS Summary of this function goes here
%   Detailed explanation goes here

    % Calculate stimulus and masks coordinates on screen.
    obj.stimulus_left_rect = CFS.get_rect(obj.screen.left.rect, ...
        obj.stimulus_position, ...
        obj.stimulus_size, ...
        obj.stimulus_padding, ...
        obj.stimulus_xy_ratio);
    obj.stimulus_right_rect =  CFS.get_rect(obj.screen.right.rect, ...
        obj.stimulus_position, ...
        obj.stimulus_size, ...
        obj.stimulus_padding, ...
        obj.stimulus_xy_ratio);

    if obj.is_left_suppression == true
        obj.stimulus_rect = obj.stimulus_right_rect;
        obj.masks_rect = CFS.get_rect(obj.screen.left.rect, ...
            obj.mask_position, ...
            obj.mask_size, ...
            0, ...
            obj.screen.left.x_pixels/obj.screen.left.y_pixels);
    else
        obj.stimulus_rect = obj.stimulus_left_rect;
        obj.masks_rect = CFS.get_rect(obj.screen.right.rect, ...
            obj.mask_position, ...
            obj.mask_size, ...
            0, ...
            obj.screen.right.x_pixels/obj.screen.right.y_pixels);
    end
end

